<ul>
<li>1.5.1 - July 2012
 <ul>
   <li>Move help external.</li>
   <li>Fix to hasChildren method.</li>
   <li>Minor code cleanup.</li>
 </ul>
</li>
<li>1.5 - October 2011
<p>A couple more useful smarty plugins.</p>
</li>
<li>1.4.10 - October 2011
<p>More Fixes for CMSMS 1.10</p>
</li>
<p>Fixes for CMSMS 1.10</p>
</li>
<li>1.4.6 - December 2010
<p>Fixed the help for the get_page_type method.</p>
</li>
<li>1.4.5 - June. 2010
<p>Adds the $cgsimple->get_page_type() method.</p>
</li>
<li>1.4.4 - Feb. 2010
   <p>Minor help fixes.</p>
   <p>Minor bug fixes.</p>
</li>
<li>1.4.3 - July, 2009
   <p>Fixes for 1.6 compatibility.</p>
</li>
<li>1.4.2 - Apr, 2009
   <p>Add the jsfriendly param to module_action_link</p>
</li>
<li>1.4.1 - Feb, 2009
   <p>Fixes to module_action_link</p>
</li>
<li>1.4 - Jan, 2009
   <p>Add the session_erase, session_put, and self_url plugins.</p>
</li>
<li>1.3.3 - Dec, 2008
    <p>No longer handle events.</li>
</li>
<li>1.3.2 - Dec, 2008
    <p>Bug Fixes.</p>
    <p>Move changelog to seperate file.</p>
    <p>Add get_sibling() smarty method.</p>
</li>
<li>1.3.1 - May, 2008
    <p>Minor fix to the module_action plugin</p>
</li>
<li>1.3 - March, 2008
  <p>Add the get_children method</p>
</li>
<li>1.2.1 - March, 2008
  <p>Minor fix for module_action_link</p>
</li>
<li>1.2 - March, 2008
  <p>Add the cgrepeat smarty plugin</p>
  <p>Add image support to the module_action_link smarty plugin</p>
  <p>Update copyright and license</p>
</li>
<li>1.1.1 - February, 2008
  <p>Fix minor problem with the module_exists method</p>
</li>
<li>1.1 - February, 2008
  <p>Added get_page_menutext() method</p>
  <p>Added module_action_link</p>
</li>
<li>1.0 - December, 2007
  <p>Initial release</p>
</li>
</ul>
