<ul>
 <li>v1.0 - April 2010
   <ul>
     <li>Initial Release.</li>
   </ul>
 </li>
 <li>v1.0.1 - April 2010
   <ul>
     <li>Minor fix to the get cart form stuff.</li>
     <li>Adds the {cgecomm_erasecart} tag.</li>
   </ul>
 </li>
 <li>v1.0.2 - May 2010
   <ul>
     <li>Adds the Store Information tab and related smarty plugins and api functions.</li>
     <li>Adds package stuff to the shipping tab to be used by upcoming shipping modules.</li>
   </ul>
 </li>
 <li>v1.1 - May 2010
   <ul>
     <li>Adds package stuff to the shipping tab to be used by upcoming shipping modules.</li>
   </ul>
 </li>
 <li>v1.2 - June 2010
   <ul>
     <li>Adds cart policy functions, and other minor enhancments.</li>
   </ul>
 </li>
 <li>v1.2.1 - August 2010
   <ul>
     <li>Adds the ability for a cart item to indicate that quantity cannot be adjusted (useful for subscriptions)</li>
     <li>Minor enhancements and fixes.</li>
   </ul>
 </li>
 <li>v1.2.2 - August 2010
   <ul>
     <li>Remove an errant die statement.</li>
   </ul>
 </li>
 <li>v1.2.3 - December 2010
   <ul>
     <li>Adds an event for before cart item add.</li>
     <li>Enahcnes functionality of the cg_ecomm_cartitem object.</li>
     <li>Re-organizez the cg_ecomm_cart method with stuff from cg_ecomm</li>
     <li>Minor bug fixes.</li>
     <li>Some minor bug fixes related to E_STRICT and E_DEPRECATED.</li>
   </ul>
 </li>
 <li>Version 1.2.4 - February 2011
  <ul>
    <li>Fixes minor preference issues on install.</li>
  </ul>
 </li>
 <li>Version 1.3 - May 2011
  <ul>
    <li>Ads a new smarty plugin to allow checking if an item is in the cart.. and a bunch of others.</li>
  </ul>
 </li>
 <li>Version 1.3.1 - May 2011
  <ul>
    <li>Minor bug fixes, and enhancements.</li>
  </ul>
 </li>
 <li>Version 1.3.2 - July 2011
  <ul>
    <li>Minor bug fix.</li>
  </ul>
 </li>
 <li>Version 1.3.3 - July 2011
  <ul>
    <li>Minor bug fix.</li>
  </ul>
 </li>
 <li>Version 1.3.5 - August 2011
  <ul><li>Bug fix.</li></ul>
 </li>
 <li>Version 1.3.11 - May 2012
  <ul><li>Adds tax shipping option.</li></ul>
 </li>
</ul>
