<ul>
    <li>Version 1.5 - january 2013<br /> 
        - add timepicker<br /> 
        - add time to datepicker<br />        
        - color picker bugfixes<br />        
    </li>
    <li>Version 1.4 - december 2012 <br /> 
        - dropdown_from_udt <br />
        - DEPRECATED: dropdown_from_module (due Smarty 3 limitation) <br />        
        - add date_format param to date picker
    </li>

    <li>Version 1.3.1 - october 2012 <br /> 
        - add file_selector <br />
        - add preview image for file_selector <br />
        - add multiple option for dropdown <br />
        - add section to admin area <br />
    </li>
    <li>Version 1.0 - november 2011 - Initial Release.</li>
</ul>